---
title: M2 Stewardship Group
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  services:
    title: services
    output: true
url: https://blakenoll.github.io/m2Fin
sass:
  style: compressed
